### ISSUE TITLE
get_account_balance_by_account_type error.

### ISSUE THREAD

**Issue by hqs988** [HuobiRDCenter/huobi_Python#10]
I tried the follow operation descriped  in github(https://github.com/huobiapi/huobi_Python. )

1. Account
2. Authentication is required.
3. balance = request_client.get_account_balance_by_account_type(AccountType.SPOT)
4. print(balance.get(0).get(0).balance)

two error happened. 

### The first :
```
from huobi import RequestClient
request_client = RequestClient(api_key="........omited.......",secret_key="......omited........")

balance = request_client.get_account_balance_by_account_type(AccountType.SPOT)
print(balance.get(0).get(0).balance)

```

the following is the error message. 

Traceback (most recent call last):
  File "C:/......./huobi/huobi_app/service/huobi_test1.py", line 4, in <module>
    balance = request_client.get_account_balance_by_account_type(AccountType.SPOT)
NameError: name 'AccountType' is not defined

I changed the code like fowlloing, the code can passed . 
balance = request_client.get_account_balance_by_account_type("spot")

but the second error happened. 

### The second
```
from huobi import RequestClient
request_client = RequestClient(api_key="........omited.......",secret_key="........omited.......")

balance = request_client.get_account_balance_by_account_type("spot")
print(balance.get(0).get(0).balance)
```

the following is the error message. 

Traceback (most recent call last):
  File "C:/......./huobi/huobi_app/service/huobi_test1.py", line 5, in <module>
    print(balance.get(0).get(0).balance)
AttributeError: 'Account' object has no attribute 'get'

**According to the wiki, the functions can run correctly.  but I failed.   don't how to use private api functions in RequestClient. Could you give me some help to fix above error?
My Mail is : hqs988@163.com
Thanks a lot.**

**Comment by NescienceSoftware** [comment]
Changing "AccountType.SPOT" to "account_type='spot'" allows their code to run properly, however the response from huobi seems to be

 " huobi.model.account.Account object at 0x00000229AA2A99E8 "

I have not been able to get past this point

**Comment by NescienceSoftware** [comment]
There are a few different issues.

First off, their documentation isnt the same as their wrapper.

You would need to change, "AccountType.SPOT" to, "account_type='SPOT'"

However even after doing this it appears that Huobi is not maintaining their API, no matter which manner I call my account, with the generic get_account_balance() and the get_account_balance_by_account_type() methods, the call returns a generic, 

"<huobi.model.account.Account object at 0x000001FD190E9E10>"

I have no idea what this really implies, but it seems that there are errors in the REST api provided by huobi in addition to the errors in this python wrapper.

**Comment by dslinux** [comment]
request_client = RequestClient(api_key=API_KEY,secret_key=SECRET_KEY)
    balance = request_client.get_account_balance_by_account_type(AccountType.SPOT)
    for TMP in balance.balances:
        if TMP.currency == PAIR : #PAIR="ethusdt"
            #print("Currency:%s,TYPE:%s,Balance:%s"%(TMP.currency,TMP.balance_type,TMP.balance))
            if TMP.balance_type == "trade" :
                #print (TMP.balance)
                return TMP.balance

you can check the class in  https://huobiapi.github.io/docs/spot/v1/cn/#2a0d0be224
