### ISSUE TITLE
Reqeusts raised exception for generic example codes.

### ISSUE THREAD

**Issue by liupgd** [HuobiRDCenter/huobi_Python#100]
Hi, I just runned your examples, but failed with exceptions:  
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.huobi.pro', port=443): Max retries exceeded with url: /v1/common/currencys (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000013D3EA12BA8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试 失败。',))`

Almost all generic example codes failed except "get_system_status.py". 

What I did?
I just cloned your repo, and then: `python setup.py install`, and then cd to examples/generic folder, run the codes.  Anything I missed? BTW, I think you should give installation specs in the Readme.

Appreciated.

**Comment by liupgd** [comment]
It's working now.

**Comment by sgz9527** [comment]
how does is work  i met the same case
