### ISSUE TITLE
Race Condition existed of websocketwatchdog

### ISSUE THREAD

**Issue by magus0219** [HuobiRDCenter/huobi_Python#19]
## Desc
websocketwatchdog can close new websocket.WebSocketApp instance when it is trying connecting(ConnectionState has race condition) because of the following logic:

websocketwatchdog.py: watch_dog_job
```python
            elif connection.state == ConnectionState.CLOSED_ON_ERROR:
                if watch_dog_instance.is_auto_connect:
                    connection.re_connect_in_delay(watch_dog_instance.connection_delay_failure)
                    pass
```

**Comment by eynzhang** [comment]
Thanks for your feedback, please try the latest master branch for version 2.
