### ISSUE TITLE
Where is the definition of CandlestickInterval? 

### ISSUE THREAD

**Issue by tzattack** [HuobiRDCenter/huobi_Python#23]
`candlestick_list = request_client.get_latest_candlestick("btcusdt", CandlestickInterval.DAY1, 20)
for candlestick in candlestick_list:
    print(candlestick.high)`

I can not find CandlestickInterval.

**Comment by eynzhang** [comment]
@tzattack you could find `class CandlestickInterval` in huobi/model/constant.py
