### ISSUE TITLE
create_order 的错误处理

### ISSUE THREAD

**Issue by featheryus** [HuobiRDCenter/huobi_Python#29]
HI，

请问下，对于create_order()，比如
order_id = request_client.create_order('eosusdt', AccountType.SPOT, OrderType.BUY_LIMIT, amount=1, price=1.011)

如果我的账户里只有1 usdt，那么这个order 会如何处理，这里的关键是按照limit price * amount，账户的usdt 是不够的：
如果当前ask_price = 0.9，amount = 10, limit price>ask price, 这个order 会按照0.9的成交吗
当前市价是ask price = 1.011，limit price<=ask_price, usdt 不足，order会直接失败掉，还是部分成交，比如只成交1/1.011?
谢谢

**Comment by eynzhang** [comment]
@featheryus 您好，该问题与SDK无关，欢迎您联系我们的客服。
