### ISSUE TITLE
Windows上安装失败

### ISSUE THREAD

**Issue by leesandao** [HuobiRDCenter/huobi_Python#35]
PYTHON为3.7.4
============
C:\Users\raynorl\AppData\Local\Continuum\anaconda3\Scripts\huobi_Python-master>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>>             

报错信息如下
=============              
Installed c:\users\raynorl\appdata\local\continuum\anaconda3\lib\site-packages\huobi_client-1.0.8-py3.7.egg
Processing dependencies for huobi-client==1.0.8
Searching for websocket-client
Reading https://pypi.org/simple/websocket-client/
Download error on https://pypi.org/simple/websocket-client/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'websocket-client' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for websocket-client
error: Could not find suitable distribution for Requirement.parse('websocket-client')

C:\Users\raynorl\AppData\Local\Continuum\anaconda3\Scripts\huobi_Python-master>python

浏览器访问“https://pypi.org/simple/websocket-client/”正常
===============
Links for websocket_client
websocket-client-0.3.tar.gz
websocket-client-0.4.tar.gz
websocket-client-0.4.1.tar.gz
websocket-client-0.5.0a.tar.gz

**Comment by eynzhang** [comment]
感谢您的反馈，之前version 1的README里的安装步骤不一定适合所有操作系统，请参照Python的帮助文档在您的操作系统进行安装。我们已经升级到version 2，并去掉了初始环境安装步骤。
