### ISSUE TITLE
error from callback <function on_close at 0x7fe4ffdf82f0>: 'WebsocketConnection' object has no attribute 'on_close'

### ISSUE THREAD

**Issue by sjtuzbx** [HuobiRDCenter/huobi_Python#41]
websocketconnection似乎没有实现on_close函数，导致程序报错
error from callback <function on_close at 0x7fe4ffdf82f0>: 'WebsocketConnection' object has no attribute 'on_close'

**Comment by eynzhang** [comment]
@sjtuzbx 感谢您的反馈，我们已经升级到了version 2，欢迎使用。

**Comment by JosephWN** [comment]
> @sjtuzbx 感谢您的反馈，我们已经升级到了version 2，欢迎使用。

我在V2.3.0中同样遇到了'WebsocketConnection' object has no attribute 'on_close'的问题，麻烦团队解决一下。
