### ISSUE TITLE
Readme 参考的获取balance代码无法使用

### ISSUE THREAD

**Issue by ksworder** [HuobiRDCenter/huobi_Python#42]
参考代码：
balance = request_client.get_account_balance_by_account_type(AccountType.SPOT)
print(balance.get(0).get(0).balance)

报错信息是：
Traceback (most recent call last):
  File "getdeposithistory.py", line 11, in <module>
    print(balance.get(0).get(0).balance)
AttributeError: 'Account' object has no attribute 'get'

**Comment by eynzhang** [comment]
我们已经升到v2版本，欢迎使用！

**Comment by Servon-Lee** [comment]
> 我们已经升到v2版本，欢迎使用！

v2的`list_obj = account_client.get_account_balance_by_subuid(sub_uid=g_sub_uid)`无法使用，请问有解决办法吗？
