### ISSUE TITLE
subscribemarketbyprice_demo.py 获取市场信息连续5个小时以后会中断连接。

### ISSUE THREAD

**Issue by ksworder** [HuobiRDCenter/huobi_Python#43]
采用这个subscribemarketbyprice_demo.py程序获取市场信息，连续5个小时接受信息以后，会中断连接，具体报错信息如下：
SubscriptionErrorUnexpected error: Connection is already closed.
SubscriptionErrorUnexpected error: 'NoneType' object has no attribute 'is_ssl'

**Comment by mkvdv-l3tech** [comment]
Hello!
I have the same error message in case of unsuccessful attempts to reconnect after breaking of network connection. 
More details in [this issue](https://github.com/HuobiRDCenter/huobi_Python/issues/47).

**Comment by eynzhang** [comment]
Thanks for your feedback, we have upgraded to version 2, and will not maintain version 1 any more.
