### ISSUE TITLE
如何获取火币交易平台的所有1分钟数据？

### ISSUE THREAD

**Issue by ksworder** [HuobiRDCenter/huobi_Python#44]
现在获取历史数据只能获取2000条。如果获取1minute的历史数据，也就能获取1天多点时间的历史数据。我想把火币平台上从2015年以来的一分钟数据获取下来，怎么获取？

**Comment by sorjor** [comment]
当前 REST API 不支持自定义时间区间，如需要历史固定时间范围的数据，请参考 Websocket API 中的 K 线接口。
