### ISSUE TITLE
AttributeError: 'WebsocketManage' object has no attribute 're_connect_in_delay'

### ISSUE THREAD

**Issue by shurmanov** [HuobiRDCenter/huobi_Python#55]
I recently upgraded to v2.0.0,

Whenever the internet disappears and then the internet comes back again, this error is striking.

```
Job "watch_dog_job (trigger: interval[0:00:01], next run at: 2020-07-08 18:52:18 +05)" raised an exception
Traceback (most recent call last):
  File "...src/huobi-client/huobi/connection/impl/websocket_watchdog.py", line 27, in watch_dog_job
    websocket_manage.re_connect_in_delay(watch_dog_obj.reconnect_after_ms)
AttributeError: 'WebsocketManage' object has no attribute 're_connect_in_delay'
```

I guess it's pretty clear, on v2.0.0 re_connect_in_delay is not implemented or removed in WebsocketManage.

How can I hotfix this with at least monkey patching?

**Comment by vipxlm** [comment]
我也遇到了，这问题怎么解？

**Comment by shurmanov** [comment]
显然，该方法没有实现。 我通过猴子补丁解决了这个问题，即我在运行时通过调用其初始化的实例类来更改了此方法。

`def patch_watch_dog_job_function():
    from huobi.connection.impl.websocket_watchdog import ConnectionState, get_current_timestamp
    import huobi.connection.impl.websocket_watchdog

    @logger.catch
    def patched_watch_dog_job(*args):
        watch_dog_obj = args[0]

        for idx, websocket_manage in enumerate(watch_dog_obj.websocket_manage_list):
            if websocket_manage.request.auto_close == True:  # setting auto close no need reconnect
                pass
            elif websocket_manage.state == ConnectionState.CONNECTED:
                if watch_dog_obj.is_auto_connect:
                    ts = get_current_timestamp() - websocket_manage.last_receive_time
                    if ts > watch_dog_obj.heart_beat_limit_ms:
                        watch_dog_obj.logger.warning("[Sub][" + str(websocket_manage.id) + "] No response from server")
                        websocket_manage.close_and_wait_reconnect(watch_dog_obj.wait_reconnect_millisecond())
            elif websocket_manage.state == ConnectionState.WAIT_RECONNECT:
                watch_dog_obj.logger.warning("[Sub] call re_connect")
                websocket_manage.re_connect()
                pass
            elif websocket_manage.state == ConnectionState.CLOSED_ON_ERROR:
                logger.critical("Smth went wrong with network")
                logger.critical(str(websocket_manage))
                if watch_dog_obj.is_auto_connect:
                    websocket_manage.re_connect()
                    pass

    huobi.connection.impl.websocket_watchdog.watch_dog_job = patched_watch_dog_job
`

**Comment by shuangbi** [comment]
already fixed in latest release
