### ISSUE TITLE
Add pip installation

### ISSUE THREAD

**Issue by EUA** [HuobiRDCenter/huobi_Python#61]
Library need to install via pip command easily.

**Comment by shuangbi** [comment]
already supported pip install with requirements.txt

**Comment by EUA** [comment]
Really? 
What is the name of the pip package?
Users can't guess pip package name.
Why it doesn't write anywhere? 
You have to indicate it at read.me file.

**Comment by Frefreak** [comment]
pypi package should be supported. Python devs expect SDK like this can be installed just using `pip install <package_name>`. From the docs I assume users are expected to clone this repo and run a pip install there?

**Comment by Leggerla** [comment]
This issue is not solved

**Comment by ton77v** [comment]
It seems there's still no pip package.. ?
