### ISSUE TITLE
url 地址是什么？ 好像现在不能访问

### ISSUE THREAD

**Issue by billni** [HuobiRDCenter/huobi_Python#68]
HUOBI_URL_PRO = "https://api.huobi.pro"
HUOBI_URL_VN = "https://api.huobi.vn"
HUOBI_URL_SO = "https://api.huobi.so"

这3个地址访问不了。

**Comment by billni** [comment]
我知道了。谢谢。

**Comment by zheng-yan-max** [comment]
> 我知道了。谢谢。

请问您怎么解决的？
