### ISSUE TITLE
Verification failure

### ISSUE THREAD

**Issue by leeeverest** [HuobiRDCenter/huobi_Python#7]
>>> from huobi import RequestClient
>>> from huobi.model import *
>>> 
>>> request_client = RequestClient(api_key="",
...                                secret_key="")
>>> balance = request_client.get_account_balance_by_account_type(AccountType.SPOT)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/trade/huobi/requstclient.py", line 243, in get_account_balance_by_account_type
    accounts = call_sync(self.request_impl.get_accounts())
  File "/home/ubuntu/trade/huobi/impl/restapiinvoker.py", line 34, in call_sync
    check_response(json_wrapper)
  File "/home/ubuntu/trade/huobi/impl/restapiinvoker.py", line 14, in check_response
    "[Executing] " + err_code + ": " + err_msg)
huobi.exception.huobiapiexception.HuobiApiException: ('ExecuteError', '[Executing] api-signature-not-valid: Signature not valid: Verification failure [校验失败]')

**Comment by macomfan** [comment]
Hi, It seems your key is invalid, could you please check if the key is still valid.

**Comment by leeeverest** [comment]
My key should be valid,because i can use it to create /cancel order and check account balance use other  trading API like ccxt.

**Comment by eynzhang** [comment]
@leeeverest we have to close this issue as it was long time ago and the code was changed a lot since then.

Feel free to raise new issue if you still have this problem.
