### ISSUE TITLE
error: package directory 'huobi' does not exist

### ISSUE THREAD

**Issue by thaob1d6** [HuobiRDCenter/huobi_Python#72]
I use "python setup.py install"  and then this error announce.

my python version: 3.8.1

![hb](https://user-images.githubusercontent.com/32641032/95153565-e65b0100-07b9-11eb-8c74-4b5ff6523856.PNG)

**Comment by shuangbi** [comment]
we cannot reproduce this issue, please check again

![pythonsdk](https://user-images.githubusercontent.com/232305/95642837-b96e5d00-0add-11eb-8006-41875992fb50.png)
