### ISSUE TITLE
API 接口都不开放访问了吗？

### ISSUE THREAD

**Issue by derweeYang** [HuobiRDCenter/huobi_Python#77]
直接调用 官方例子
python ./get_exchange_info.py 

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.huobi.pro', port=443): Max retries exceeded with url: /v1/common/currencys (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f794ea7b8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by eynzhang** [comment]
@derweeYang The API is always opening and it may be not available in China mainland, please try to open the GET request in your explorer to double check.
