### ISSUE TITLE
关于某国内可用网址：

### ISSUE THREAD

**Issue by wizcs** [HuobiRDCenter/huobi_Python#80]
关于api.  huobi  .be这个网址
1.如果我更改constant中的url选项没起作用，但我在方法中传参就可以使用了。
2.api.huobi.be在同一网络环境中的windows上可以使用和ping通，在linux上ping则显示system error，我怀疑这可能跟DNS污染有关，但没什么想法，国内调试过于麻烦了，我不想获得关于此网址的什么帮助，我只想知道这个的原因——到底为什么windows可以但linux却不行！太奇怪了，DNS等都指向同一地址，api.huobi.pro这网址就都没问题！！这太奇怪了

**Comment by wizcs** [comment]
问题1应该是pip某种缓存的事儿，重启就好了

**Comment by ticaleenlx** [comment]
> 关于api. huobi .be这个网址
> 1.如果我更改constant中的url选项没起作用，但我在方法中传参就可以使用了。
> 2.api.huobi.be在同一网络环境中的windows上可以使用和ping通，在linux上ping则显示system error，我怀疑这可能跟DNS污染有关，但没什么想法，国内调试过于麻烦了，我不想获得关于此网址的什么帮助，我只想知道这个的原因——到底为什么windows可以但linux却不行！太奇怪了，DNS等都指向同一地址，api.huobi.pro这网址就都没问题！！这太奇怪了

问题2，我这刚开始也不行，设置了/etc/resolv.conf nameserver 114.114.114.114 就可以了

**Comment by eynzhang** [comment]
国内访问API可以使用临时的不稳定地址api.huobi.de.com
