### ISSUE TITLE
rest api (/swap-api/v1/swap_balance_valuation} returns 404

### ISSUE THREAD

**Issue by ChengGuanghui** [HuobiRDCenter/huobi_Python#92]
Now the swap api such as /swap-api/v1/swap_balance_valuation is ready or not yet?

I try to call it but return with "404, not found'

**Comment by eynzhang** [comment]
@ChengGuanghui Your feedback is about the Swap API, you can contact Swap support team or raise comments on Swap SDK repository https://github.com/hbdmapi
