### ISSUE TITLE
[Executing] order-source-invalid: invalid order source `spot-api`

### ISSUE THREAD

**Issue by biaohanli** [HuobiRDCenter/huobi_Python#95]
下单的代码是
trade_client.create_order(symbol='btcusdt', account_id=account_id, order_type=OrderType.BUY_LIMIT,
                                               source='spot-api', amount=0.0001, price=1.29)
order source换成spot-api或者api都不行
错如上错误

**Comment by JxiaoC** [comment]
我也遇到了..不知道咋回事儿

**Comment by JxiaoC** [comment]
> 我也遇到了..不知道咋回事儿

哦, 用错了账号id, 应该用Account Type : spot这个账号
